version: "3"

services:
  php:
    build: "./php/"
    volumes:
      - ./www/:/var/www/html/
    depends_on:
      - mysql
  apache:
    build: "./apache/"
    depends_on:
      - php
      - mysql
    ports:
      - "8080:80"
    volumes:
      - ./www/:/var/www/html/
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_database
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  composer:
    image: composer:latest
    command: ["composer", "install"]
    volumes:
      - /var/www/docker-study.loc/recipe-05/php:/app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
